minio:
    accesskeyid: Gx0S3h31P8SfmOWhm3Tg
    endpoint: localhost:9000
    secretaccesskey: XAqfnX6Q77PhtEUhyjziZj8bsPpz9PoSLtgSh1yY
    usessl: false
user:
    role: Admin
    token: 5fRAiOM6o49cGiP7
    username: admin
